const flags = {
    "Afrikaans": "🇿🇦",
    "Albanian": "🇦🇱",
    "Arabic": "🇸🇦",
    "Armenian": "🇦🇲",
    "Australian": "🇦🇺",
    "Bengali": "🇮🇳",
    "Bosnian": "🇧🇦",
    "Catalan": "🇪🇸",
    "Chinese": "🇨🇳",
    "Croatian": "🇭🇷",
    "Czech": "🇨🇿",
    "Danish": "🇩🇰",
    "Dutch": "🇳🇱",
    "English": "🇬🇧",
    "Esperanto": "🌐",
    "Estonian": "🇪🇪",
    "Filipino": "🇵🇭",
    "Finnish": "🇫🇮",
    "French": "🇫🇷",
    "German": "🇩🇪",
    "Greek": "🇬🇷",
    "Hindi": "🇮🇳",
    "Hungarian": "🇭🇺",
    "Icelandic": "🇮🇸",
    "Indonesian": "🇮🇩",
    "Italian": "🇮🇹",
    "Japanese": "🇯🇵",
    "Korean": "🇰🇷",
    "Latin": "🏛️",
    "Latvian": "🇱🇻",
    "Macedonian": "🇲🇰",
    "Moldavian": "🇲🇩",
    "Montenegrin": "🇲🇪",
    "Nepali": "🇳🇵",
    "Norwegian": "🇳🇴",
    "Polish": "🇵🇱",
    "Portuguese": "🇵🇹",
    "Romanian": "🇷🇴",
    "Russian": "🇷🇺",
    "Serbian": "🇷🇸",
    "Serbo-Croatian": "🇭🇷",
    "Sinhala": "🇱🇰",
    "Slovak": "🇸🇰",
    "Spanish": "🇪🇸",
    "Swahili": "🇹🇿",
    "Swedish": "🇸🇪",
    "Tamil": "🇮🇳",
    "Thai": "🇹🇭",
    "Turkish": "🇹🇷",
    "Ukrainian": "🇺🇦",
    "Vietnamese": "🇻🇳",
    "Welsh": "🏴󠁧󠁢󠁷󠁬󠁳󠁿"
};

export default flags;