const voiceLanguageOptions = [
  { code: "UK English Female", name: "UK English Female" },
  { code: "UK English Male", name: "UK English Male" },
  { code: "US English Female", name: "US English Female" },
  { code: "US English Male", name: "US English Male" },
  { code: "Arabic Male", name: "Arabic Male" },
  { code: "Arabic Female", name: "Arabic Female" },
  { code: "Armenian Male", name: "Armenian Male" },
  { code: "Australian Female", name: "Australian Female" },
  { code: "Australian Male", name: "Australian Male" },
  { code: "Bangla Bangladesh Female", name: "Bangla Bangladesh Female" },
  { code: "Bangla Bangladesh Male", name: "Bangla Bangladesh Male" },
  { code: "Bangla India Female", name: "Bangla India Female" },
  { code: "Bangla India Male", name: "Bangla India Male" },
  { code: "Brazilian Portuguese Female", name: "Brazilian Portuguese Female" },
  { code: "Chinese Female", name: "Chinese Female" },
  { code: "Chinese Male", name: "Chinese Male" },
  { code: "Chinese (Hong Kong) Female", name: "Chinese (Hong Kong) Female" },
  { code: "Chinese (Hong Kong) Male", name: "Chinese (Hong Kong) Male" },
  { code: "Chinese Taiwan Female", name: "Chinese Taiwan Female" },
  { code: "Chinese Taiwan Male", name: "Chinese Taiwan Male" },
  { code: "Czech Female", name: "Czech Female" },
  { code: "Danish Female", name: "Danish Female" },
  { code: "Deutsch Female", name: "Deutsch Female" },
  { code: "Deutsch Male", name: "Deutsch Male" },
  { code: "Dutch Female", name: "Dutch Female" },
  { code: "Dutch Male", name: "Dutch Male" },
  { code: "Estonian Male", name: "Estonian Male" },
  { code: "Filipino Female", name: "Filipino Female" },
  { code: "Finnish Female", name: "Finnish Female" },
  { code: "French Female", name: "French Female" },
  { code: "French Male", name: "French Male" },
  { code: "French Canadian Female", name: "French Canadian Female" },
  { code: "French Canadian Male", name: "French Canadian Male" },
  { code: "Greek Female", name: "Greek Female" },
  { code: "Hindi Female", name: "Hindi Female" },
  { code: "Hindi Male", name: "Hindi Male" },
  { code: "Hungarian Female", name: "Hungarian Female" },
  { code: "Indonesian Female", name: "Indonesian Female" },
  { code: "Indonesian Male", name: "Indonesian Male" },
  { code: "Italian Female", name: "Italian Female" },
  { code: "Italian Male", name: "Italian Male" },
  { code: "Japanese Female", name: "Japanese Female" },
  { code: "Japanese Male", name: "Japanese Male" },
  { code: "Korean Female", name: "Korean Female" },
  { code: "Korean Male", name: "Korean Male" },
  { code: "Latin Male", name: "Latin Male" },
  { code: "Nepali", name: "Nepali" },
  { code: "Norwegian Female", name: "Norwegian Female" },
  { code: "Norwegian Male", name: "Norwegian Male" },
  { code: "Polish Female", name: "Polish Female" },
  { code: "Polish Male", name: "Polish Male" },
  { code: "Portuguese Female", name: "Portuguese Female" },
  { code: "Portuguese Male", name: "Portuguese Male" },
  { code: "Romanian Female", name: "Romanian Female" },
  { code: "Russian Female", name: "Russian Female" },
  { code: "Sinhala", name: "Sinhala" },
  { code: "Slovak Female", name: "Slovak Female" },
  { code: "Spanish Female", name: "Spanish Female" },
  { code: "Spanish Latin American Female", name: "Spanish Latin American Female" },
  { code: "Spanish Latin American Male", name: "Spanish Latin American Male" },
  { code: "Swedish Female", name: "Swedish Female" },
  { code: "Swedish Male", name: "Swedish Male" },
  { code: "Tamil Female", name: "Tamil Female" },
  { code: "Tamil Male", name: "Tamil Male" },
  { code: "Thai Female", name: "Thai Female" },
  { code: "Thai Male", name: "Thai Male" },
  { code: "Turkish Female", name: "Turkish Female" },
  { code: "Turkish Male", name: "Turkish Male" },
  { code: "Ukrainian Female", name: "Ukrainian Female" },
  { code: "Vietnamese Female", name: "Vietnamese Female" },
  { code: "Vietnamese Male", name: "Vietnamese Male" },
  { code: "Afrikaans Male", name: "Afrikaans Male" },
  { code: "Albanian Male", name: "Albanian Male" },
  { code: "Bosnian Male", name: "Bosnian Male" },
  { code: "Catalan Male", name: "Catalan Male" },
  { code: "Croatian Male", name: "Croatian Male" },
  { code: "Esperanto Male", name: "Esperanto Male" },
  { code: "Icelandic Female", name: "Icelandic Female" },
  { code: "Latvian Male", name: "Latvian Male" },
  { code: "Macedonian Male", name: "Macedonian Male" },
  { code: "Moldavian Female", name: "Moldavian Female" },
  { code: "Montenegrin Male", name: "Montenegrin Male" },
  { code: "Serbian Male", name: "Serbian Male" },
  { code: "Serbo-Croatian Male", name: "Serbo-Croatian Male" },
  { code: "Swahili Male", name: "Swahili Male" },
  { code: "Welsh Male", name: "Welsh Male" },
  { code: "Fallback UK Female", name: "Fallback UK Female" }
];

export default voiceLanguageOptions;