const voiceLanguageOptions = [
  { code: "UK English Female", name: "UK English Female", flag: "🇬🇧" },
  { code: "UK English Male", name: "UK English Male", flag: "🇬🇧" },
  { code: "US English Female", name: "US English Female", flag: "🇬🇧" },
  { code: "US English Male", name: "US English Male", flag: "🇬🇧" },
  { code: "Arabic Male", name: "Arabic Male", flag: "🇸🇦" },
  { code: "Arabic Female", name: "Arabic Female", flag: "🇸🇦" },
  { code: "Armenian Male", name: "Armenian Male", flag: "🇦🇲" },
  { code: "Australian Female", name: "Australian Female", flag: "🇦🇺" },
  { code: "Australian Male", name: "Australian Male", flag: "🇦🇺" },
  { code: "Bangla Bangladesh Female", name: "Bangla Bangladesh Female", flag: "🇮🇳" },
  { code: "Bangla Bangladesh Male", name: "Bangla Bangladesh Male", flag: "🇮🇳" },
  { code: "Bangla India Female", name: "Bangla India Female", flag: "🇮🇳" },
  { code: "Bangla India Male", name: "Bangla India Male", flag: "🇮🇳" },
  { code: "Brazilian Portuguese Female", name: "Brazilian Portuguese Female", flag: "🇵🇹" },
  { code: "Chinese Female", name: "Chinese Female", flag: "🇨🇳" },
  { code: "Chinese Male", name: "Chinese Male", flag: "🇨🇳" },
  { code: "Chinese (Hong Kong) Female", name: "Chinese (Hong Kong) Female", flag: "🇨🇳" },
  { code: "Chinese (Hong Kong) Male", name: "Chinese (Hong Kong) Male", flag: "🇨🇳" },
  { code: "Chinese Taiwan Female", name: "Chinese Taiwan Female", flag: "🇨🇳" },
  { code: "Chinese Taiwan Male", name: "Chinese Taiwan Male", flag: "🇨🇳" },
  { code: "Czech Female", name: "Czech Female", flag: "🇨🇿" },
  { code: "Danish Female", name: "Danish Female", flag: "🇩🇰" },
  { code: "Deutsch Female", name: "Deutsch Female", flag: "🇩🇪" },
  { code: "Deutsch Male", name: "Deutsch Male", flag: "🇩🇪" },
  { code: "Dutch Female", name: "Dutch Female", flag: "🇳🇱" },
  { code: "Dutch Male", name: "Dutch Male", flag: "🇳🇱" },
  { code: "Estonian Male", name: "Estonian Male", flag: "🇪🇪" },
  { code: "Filipino Female", name: "Filipino Female", flag: "🇵🇭" },
  { code: "Finnish Female", name: "Finnish Female", flag: "🇫🇮" },
  { code: "French Female", name: "French Female", flag: "🇫🇷" },
  { code: "French Male", name: "French Male", flag: "🇫🇷" },
  { code: "French Canadian Female", name: "French Canadian Female", flag: "🇫🇷" },
  { code: "French Canadian Male", name: "French Canadian Male", flag: "🇫🇷" },
  { code: "Greek Female", name: "Greek Female", flag: "🇬🇷" },
  { code: "Hindi Female", name: "Hindi Female", flag: "🇮🇳" },
  { code: "Hindi Male", name: "Hindi Male", flag: "🇮🇳" },
  { code: "Hungarian Female", name: "Hungarian Female", flag: "🇭🇺" },
  { code: "Indonesian Female", name: "Indonesian Female", flag: "🇮🇩" },
  { code: "Indonesian Male", name: "Indonesian Male", flag: "🇮🇩" },
  { code: "Italian Female", name: "Italian Female", flag: "🇮🇹" },
  { code: "Italian Male", name: "Italian Male", flag: "🇮🇹" },
  { code: "Japanese Female", name: "Japanese Female", flag: "🇯🇵" },
  { code: "Japanese Male", name: "Japanese Male", flag: "🇯🇵" },
  { code: "Korean Female", name: "Korean Female", flag: "🇰🇷" },
  { code: "Korean Male", name: "Korean Male", flag: "🇰🇷" },
  { code: "Latin Male", name: "Latin Male", flag: "🏛️" },
  { code: "Nepali", name: "Nepali", flag: "🇳🇵" },
  { code: "Norwegian Female", name: "Norwegian Female", flag: "🇳🇴" },
  { code: "Norwegian Male", name: "Norwegian Male", flag: "🇳🇴" },
  { code: "Polish Female", name: "Polish Female", flag: "🇵🇱" },
  { code: "Polish Male", name: "Polish Male", flag: "🇵🇱" },
  { code: "Portuguese Female", name: "Portuguese Female", flag: "🇵🇹" },
  { code: "Portuguese Male", name: "Portuguese Male", flag: "🇵🇹" },
  { code: "Romanian Female", name: "Romanian Female", flag: "🇷🇴" },
  { code: "Russian Female", name: "Russian Female", flag: "🇷🇺" },
  { code: "Sinhala", name: "Sinhala", flag: "🇱🇰" },
  { code: "Slovak Female", name: "Slovak Female", flag: "🇸🇰" },
  { code: "Spanish Female", name: "Spanish Female", flag: "🇪🇸" },
  { code: "Spanish Latin American Female", name: "Spanish Latin American Female", flag: "🇪🇸" },
  { code: "Spanish Latin American Male", name: "Spanish Latin American Male", flag: "🇪🇸" },
  { code: "Swedish Female", name: "Swedish Female", flag: "🇸🇪" },
  { code: "Swedish Male", name: "Swedish Male", flag: "🇸🇪" },
  { code: "Tamil Female", name: "Tamil Female", flag: "🇮🇳" },
  { code: "Tamil Male", name: "Tamil Male", flag: "🇮🇳" },
  { code: "Thai Female", name: "Thai Female", flag: "🇹🇭" },
  { code: "Thai Male", name: "Thai Male", flag: "🇹🇭" },
  { code: "Turkish Female", name: "Turkish Female", flag: "🇹🇷" },
  { code: "Turkish Male", name: "Turkish Male", flag: "🇹🇷" },
  { code: "Ukrainian Female", name: "Ukrainian Female", flag: "🇺🇦" },
  { code: "Vietnamese Female", name: "Vietnamese Female", flag: "🇻🇳" },
  { code: "Vietnamese Male", name: "Vietnamese Male", flag: "🇻🇳" },
  { code: "Afrikaans Male", name: "Afrikaans Male", flag: "🇿🇦" },
  { code: "Albanian Male", name: "Albanian Male", flag: "🇦🇱" },
  { code: "Bosnian Male", name: "Bosnian Male", flag: "🇧🇦" },
  { code: "Catalan Male", name: "Catalan Male", flag: "🇪🇸" },
  { code: "Croatian Male", name: "Croatian Male", flag: "🇭🇷" },
  { code: "Esperanto Male", name: "Esperanto Male", flag: "🌐" },
  { code: "Icelandic Female", name: "Icelandic Female", flag: "🇮🇸" },
  { code: "Latvian Male", name: "Latvian Male", flag: "🇱🇻" },
  { code: "Macedonian Male", name: "Macedonian Male", flag: "🇲🇰" },
  { code: "Moldavian Female", name: "Moldavian Female", flag: "🇲🇩" },
  { code: "Montenegrin Male", name: "Montenegrin Male", flag: "🇲🇪" },
  { code: "Serbian Male", name: "Serbian Male", flag: "🇷🇸" },
  { code: "Serbo-Croatian Male", name: "Serbo-Croatian Male", flag: "🇭🇷" },
  { code: "Swahili Male", name: "Swahili Male", flag: "🇹🇿" },
  { code: "Welsh Male", name: "Welsh Male", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  { code: "Fallback UK Female", name: "Fallback UK Female", flag: "🇬🇧" }
];

export default voiceLanguageOptions;